# Generated by Django 3.1.3 on 2021-05-06 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=1000)),
                ('question2', models.CharField(max_length=1000)),
                ('question3', models.CharField(max_length=1000)),
                ('question4', models.CharField(max_length=1000)),
                ('question5', models.CharField(max_length=1000)),
                ('question6', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Attitude',
            },
        ),
        migrations.CreateModel(
            name='Empathy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=1000)),
                ('question2', models.CharField(max_length=1000)),
                ('question3', models.CharField(max_length=1000)),
                ('question4', models.CharField(max_length=1000)),
                ('question5', models.CharField(max_length=1000)),
                ('question6', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Empathy',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=1000)),
                ('question2', models.CharField(max_length=1000)),
                ('question3', models.CharField(max_length=1000)),
                ('question4', models.CharField(max_length=1000)),
                ('question5', models.CharField(max_length=1000)),
                ('question6', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Policy',
            },
        ),
        migrations.CreateModel(
            name='Professionalism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=1000)),
                ('question2', models.CharField(max_length=1000)),
                ('question3', models.CharField(max_length=1000)),
                ('question4', models.CharField(max_length=1000)),
                ('question5', models.CharField(max_length=1000)),
                ('question6', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Professionalism',
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=1000)),
                ('question2', models.CharField(max_length=1000)),
                ('question3', models.CharField(max_length=1000)),
                ('question4', models.CharField(max_length=1000)),
                ('question5', models.CharField(max_length=1000)),
                ('question6', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Teaching',
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('totalScore', models.FloatField(blank=True, default=0, null=True)),
                ('duration', models.FloatField(blank=True, default=0, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scores',
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('topic', models.CharField(max_length=20)),
                ('culturalDestructiveness', models.CharField(max_length=5)),
                ('culturalIncapacity', models.CharField(max_length=5)),
                ('culturalBlindness', models.CharField(max_length=5)),
                ('culturalPreCompetence', models.CharField(max_length=5)),
                ('culturalCompetence', models.CharField(max_length=5)),
                ('culturalProficiency', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('duration', models.FloatField(blank=True, default=0, null=True)),
                ('scores', models.JSONField(default=list)),
                ('comment1', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('comment2', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Responses',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profile', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('q1', models.CharField(max_length=500)),
                ('q2', models.CharField(max_length=500)),
                ('q3', models.CharField(max_length=500)),
                ('q4', models.CharField(max_length=500)),
                ('q5', models.CharField(max_length=500)),
                ('q6', models.CharField(max_length=500)),
                ('q7', models.CharField(max_length=500)),
                ('q8', models.CharField(max_length=500)),
                ('q9', models.CharField(max_length=500)),
                ('q10', models.CharField(max_length=500)),
                ('q11', models.CharField(max_length=500)),
                ('q12', models.CharField(max_length=500)),
                ('q13', models.CharField(max_length=500)),
                ('q14', models.CharField(max_length=500)),
                ('q15', models.CharField(max_length=500)),
                ('q16', models.CharField(max_length=500)),
                ('q17', models.CharField(max_length=500)),
                ('q18', models.CharField(max_length=500)),
                ('q19', models.CharField(max_length=500)),
                ('q20', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('duration', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PreSurvey',
            },
        ),
        migrations.CreateModel(
            name='PostSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('q1', models.CharField(max_length=500)),
                ('q2', models.CharField(max_length=500)),
                ('q3', models.CharField(max_length=500)),
                ('q4', models.CharField(max_length=500)),
                ('q5', models.CharField(max_length=500)),
                ('q6', models.CharField(max_length=500)),
                ('q7', models.CharField(max_length=500)),
                ('q8', models.JSONField(default=list)),
                ('q9', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PostSurvey',
            },
        ),
        migrations.CreateModel(
            name='FinalFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('q1', models.CharField(max_length=500)),
                ('q2', models.CharField(max_length=500)),
                ('q3', models.CharField(max_length=500)),
                ('q4', models.CharField(max_length=500)),
                ('q5', models.CharField(max_length=500)),
                ('q6', models.CharField(max_length=500)),
                ('q7', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FinalFeedback',
            },
        ),
        migrations.CreateModel(
            name='CPCQResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('culturalDestructivenessresponse', models.JSONField(blank=True, default='', null=True)),
                ('culturalIncapacityresponse', models.JSONField(blank=True, default='', null=True)),
                ('culturalBlindnessresponse', models.JSONField(blank=True, default='', null=True)),
                ('culturalPreCompetenceresponse', models.JSONField(blank=True, default='', null=True)),
                ('culturalCompetenceresponse', models.JSONField(blank=True, default='', null=True)),
                ('culturalProficiencyresponse', models.JSONField(blank=True, default='', null=True)),
                ('duration', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(default=False)),
                ('scores', models.JSONField(default=list)),
                ('response_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.responses')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CPCQResponses',
                'ordering': ['topic'],
            },
        ),
        migrations.CreateModel(
            name='cpcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('choices', models.CharField(blank=True, default='', max_length=3999, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CPCQ',
            },
        ),
    ]
