# Generated by Django 3.1.3 on 2021-05-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='status',
            new_name='email_status',
        ),
    ]
