# Generated by Django 3.1.3 on 2021-05-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210506_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpcqresponses',
            name='comment1',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='cpcqresponses',
            name='comment2',
            field=models.JSONField(default=list),
        ),
    ]
