# Generated by Django 3.1.3 on 2021-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210506_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsurvey',
            name='q10',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='q21',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='q8',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='q9',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='q20',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
