# Generated by Django 3.1.3 on 2021-05-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210520_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSurveyQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question2', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question3', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question4', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question5', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question6', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question7', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question8', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question9', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question10', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreSurveyQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question2', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question3', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question4', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question5', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question6', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question7', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question8', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question9', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question10', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question11', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question12', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question13', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question14', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question15', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question16', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question17', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question18', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question19', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question20', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('question21', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
