# Generated by Django 3.1.3 on 2021-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_postsurveyquestions_presurveyquestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsurveyquestions',
            options={'verbose_name_plural': 'Post Survey Questions'},
        ),
        migrations.AlterModelOptions(
            name='presurveyquestions',
            options={'verbose_name_plural': 'Pre Survey Questions'},
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presurvey',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
