# Generated by Django 3.1.3 on 2021-05-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210525_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presurveystatus', models.BooleanField(default=False)),
                ('responsesstatus', models.BooleanField(default=False)),
                ('cpcqstatus', models.BooleanField(default=False)),
                ('finalfeedbackstatus', models.BooleanField(default=False)),
                ('scoresstatus', models.BooleanField(default=False)),
                ('postsurveystatus', models.BooleanField(default=False)),
            ],
        ),
    ]
