# Generated by Django 3.1.3 on 2021-05-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210525_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presurvey',
            name='q7',
            field=models.JSONField(default=list),
        ),
    ]
