# Generated by Django 3.1.3 on 2021-06-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210525_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='comment1',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='comment2',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='scores',
        ),
    ]
