# Generated by Django 3.1.3 on 2021-06-01 13:49

from django.db import migrations
import fields.JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210601_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpcqresponses',
            name='comment1',
            field=fields.JSONField.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpcqresponses',
            name='comment2',
            field=fields.JSONField.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpcqresponses',
            name='scores',
            field=fields.JSONField.JSONField(blank=True, null=True),
        ),
    ]
